steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/daurinpoin:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/daurinpoin:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'daurinpoin'
      - '--image=gcr.io/$PROJECT_ID/daurinpoin:$COMMIT_SHA'
      - '--region=asia-southeast2'
      - '--cpu=4'
      - '--memory=4Gi'
      - '--allow-unauthenticated'
      - '--set-secrets=DB_HOST=db_host:latest,DB_USER=db_username:latest,DB_PASSWORD=db_password:latest,SECRET_KEY=daurinpoin_secret_key:latest,HASH_KEY=daurinpoin_hash_key:latest,MAIL_HOST=daurinpoin_mail_host:latest,MAIL_PORT=daurinpoin_mail_port:latest,MAIL_USER=daurinpoin_mail_user:latest,MAIL_PASSWORD=daurinpoin_mail_password:latest,MAPS_KEY=daurinpoin_maps_key:latest'

images:
  - 'gcr.io/$PROJECT_ID/daurinpoin:$COMMIT_SHA'

logsBucket: 'gs://daurinpoin-buckets/logs'
